Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -18,3 +18,14 @@ steps:
     sonarQubeRunAnalysis: false
     spotBugsAnalysis: false
   displayName: Build/TestCoverage
+
+- task: Bash@3
+  inputs:
+    targetType: 'inline'
+    script: |
+      minimum_coverage=$(grep "minimum=" build.gradle | grep -o "[0-9]*\.[0-9]*")
+      coverage=$(grep "LINE" build/reports/jacoco/test/html/index.html | head -n1 | grep -o "[0-9]*\.[0-9]*")
+      if (( $(echo "$coverage < $minimum_coverage" |bc -l) )); then
+        echo "Code coverage ($coverage) is less than the required minimum ($minimum_coverage)"
+        exit 1
+      fi
